ALTER TABLE KINGDOM MODIFY NAME NOT NULL;
ALTER TABLE PHYLUM MODIFY KINGDOM_ID NOT NULL;
ALTER TABLE CLASS MODIFY PHYLUM_ID NOT NULL;
ALTER TABLE ORDEN MODIFY CLASS_ID NOT NULL;
ALTER TABLE FAMILY MODIFY ORDEN_ID NOT NULL;
ALTER TABLE GENUS MODIFY FAMILY_ID NOT NULL;
ALTER TABLE SPECIES MODIFY GENUS_ID NOT NULL;

---------------------------- rename them all for taxon_ancestor_id-------------------------
ALTER TABLE PHYLUM
RENAME COLUMN KINGDOM_ID TO taxon_ancestor_id;

ALTER TABLE CLASS
RENAME COLUMN PHYLUM_ID TO taxon_ancestor_id;

ALTER TABLE ORDEN
RENAME COLUMN CLASS_ID TO taxon_ancestor_id;

ALTER TABLE FAMILY
RENAME COLUMN ORDEN_ID TO taxon_ancestor_id;

ALTER TABLE GENUS
RENAME COLUMN FAMILY_ID TO taxon_ancestor_id;

ALTER TABLE SPECIES
RENAME COLUMN GENUS_ID TO taxon_ancestor_id;



ALTER TABLE IMAGE MODIFY(
    PERSON_ID NOT NULL,
    TAXON_ID NOT NULL,
    taken_image_date NOT NULL,
    image_date NOT NULL,
    geographic_coordenates_id NOT NULL,
    image_owner_id NOT NULL,
    figure_id NOT NULL,
    use_license NOT NULL
);

ALTER TABLE OBSERVATION MODIFY (
    NOTE NOT NULL,
    IMAGE_ID NOT NULL
    );

ALTER TABLE geographic_coordenates MODIFY(
    LATITUDE  NOT NULL,
    LONGITUDE   NOT NULL);

ALTER TABLE PERSON MODIFY(
    NAME NOT NULL,
    LAST_NAME NOT NULL,
    COUNTRY_ID NOT NULL,
    ADDRESS NOT NULL
);
ALTER TABLE INDENTIFICATION MODIFY(
    QUALITY_LEVEL NOT NULL,
    OBSERVATION_ID NOT NULL,
    IDENTIFICATION_PERSON_ID NOT NULL
    -- IDENTIFICATION_DATE NOT NULL
);
RENAME INDENTIFICATION to IDENTIFICATION;



ALTER TABLE country MODIFY (
    NAME NOT NULL
    );

ALTER TABLE image_owner MODIFY (
    NAME NOT NULL
    );


ALTER TABLE taxon add (
    top_hierarchy_id INT NOT NULL,
    top_hierarchy_table VARCHAR2(50) NOT NULL,
    SPECIES_ID INT,
    CONSTRAINT fk_SPECIES_ID FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES(id)
    );
    
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
ALTER TABLE  MODIFY  NOT NULL;
