ALTER TABLE image
DROP COLUMN FIGURE_ID;
ALTER TABLE image
ADD FIGURE_ID INT;

ALTER TABLE image
ADD CONSTRAINT fkFIGURE_ID
FOREIGN KEY (FIGURE_ID)
REFERENCES FIGURE(id);

ALTER TABLE GEOGRAPHIC_COORDENATES
add LONGITUDE VARCHAR2(200);


ALTER TABLE INDENTIFICATION
ADD Taxon_Id INT;

ALTER TABLE INDENTIFICATION
ADD CONSTRAINT fkTaxon_Id
FOREIGN KEY (Taxon_Id)
REFERENCES Taxon(id);

ALTER TABLE OBSERVATION
ADD Taxon_Id INT;

ALTER TABLE OBSERVATION
ADD CONSTRAINT taxon_Id_FK
FOREIGN KEY (Taxon_Id)
REFERENCES Taxon(id);

ALTER TABLE SPECIES
add NAME varchar2(200);