ALTER TABLE FIGURE
RENAME COLUMN FIGURE_URL TO FIGURE_URL;

ALTER TABLE FIGURE ADD
    FIGURE_URL VARCHAR2(10000) NOT NULL;

alter table FIGURE DROP COLUMN FIGURE_URL;
----- alterar todas las tablas para que el taxon_ancestor_id sea unica
----- para todas y cada una de las tablas


----------ME VOLVI CRAZY

create table KINGDOM(
    id NUMBER DEFAULT TAXON_ANCESTOR_ID.NEXTVAL PRIMARY KEY,
    name varchar2(30) NOT NULL
);



create table PHYLUM(
    id NUMBER DEFAULT TAXON_ANCESTOR_ID.NEXTVAL PRIMARY KEY,
    name varchar2(300) NOT NULL,
    TAXON_ANCESTOR_ID INT,
    CONSTRAINT FK_Kingdom_id FOREIGN KEY (TAXON_ANCESTOR_ID) REFERENCES Kingdom(id)
);

create table CLASS(
    id NUMBER DEFAULT TAXON_ANCESTOR_ID.NEXTVAL PRIMARY KEY,
    name varchar2(300) NOT NULL,
    TAXON_ANCESTOR_ID INT NOT NULL,
    CONSTRAINT FK_PHYLUM_id FOREIGN KEY (TAXON_ANCESTOR_ID) REFERENCES PHYLUM(id)
);

create table ORDEN(
    id NUMBER DEFAULT TAXON_ANCESTOR_ID.NEXTVAL PRIMARY KEY,
    name varchar2(300) NOT NULL,
    TAXON_ANCESTOR_ID INT NOT NULL,
    CONSTRAINT FK_CLASS_id FOREIGN KEY (TAXON_ANCESTOR_ID) REFERENCES CLASS(id)
);

create table FAMILY(
    id NUMBER DEFAULT TAXON_ANCESTOR_ID.NEXTVAL PRIMARY KEY,
    name varchar2(300) NOT NULL,
    TAXON_ANCESTOR_ID INT NOT NULL,
    CONSTRAINT FK_ORDEN_id FOREIGN KEY (TAXON_ANCESTOR_ID) REFERENCES ORDEN(id)
);

create table GENUS(
    id NUMBER DEFAULT TAXON_ANCESTOR_ID.NEXTVAL PRIMARY KEY,
    name varchar2(300) NOT NULL,
    TAXON_ANCESTOR_ID INT NOT NULL,
    CONSTRAINT FK_FAMILY_id FOREIGN KEY (TAXON_ANCESTOR_ID) REFERENCES FAMILY(id)
);

create table SPECIES(
    id NUMBER DEFAULT TAXON_ANCESTOR_ID.NEXTVAL PRIMARY KEY,
    COMMON_NAME varchar2(300),
    name varchar2(300) NOT NULL,
    TAXON_ANCESTOR_ID INT NOT NULL,
    CONSTRAINT FK_GENUS_id FOREIGN KEY (TAXON_ANCESTOR_ID) REFERENCES GENUS(id)
);

select * from species;



alter table IMAGE drop COLUMN KINGDOM_ID;
alter table image add TAKEN_IMAGE_DATE VARCHAR2(15);

alter TABLE FIGURE modify FIGURE_URL varchar2(2000);