DELETE FROM KINGDOM;
DELETE FROM ORDEN;
DELETE FROM FAMILY;
DELETE FROM GENUS;
DELETE FROM PHYLUM;
DELETE FROM CLASS;
DELETE FROM SPECIES;


ALTER TABLE IMAGE
ADD taken_image_date DATE;


ALTER TABLE OBSERVATION
DROP COLUMN TAXON_ID;

ALTER TABLE INDENTIFICATION
DROP COLUMN TAXON_ID;



--ALTER TABLE TAXON
--DROP COLUMN KINGDOM_ID;
ALTER TABLE TAXON
DROP COLUMN PHYLUM_ID;
ALTER TABLE TAXON
DROP COLUMN CLASS_ID;
ALTER TABLE TAXON
DROP COLUMN ORDEN_ID;
ALTER TABLE TAXON
DROP COLUMN FAMILY_ID;
ALTER TABLE TAXON
DROP COLUMN SPECIES_ID;
ALTER TABLE TAXON
DROP COLUMN GENUS_ID;

ALTER TABLE PHYLUM
ADD KINGDOM_ID INT;
ALTER TABLE PHYLUM
ADD CONSTRAINT fk_KINGDOM_ID
FOREIGN KEY (KINGDOM_ID)
REFERENCES KINGDOM(id);

ALTER TABLE CLASS
ADD PHYLUM_ID INT;
ALTER TABLE CLASS
ADD CONSTRAINT fk_PHYLUM_ID
FOREIGN KEY (PHYLUM_ID)
REFERENCES PHYLUM(id);

ALTER TABLE ORDEN
ADD CLASS_ID INT;
ALTER TABLE ORDEN
ADD CONSTRAINT fk_CLASS_ID
FOREIGN KEY (CLASS_ID)
REFERENCES CLASS(id);

ALTER TABLE FAMILY
ADD ORDEN_ID INT;
ALTER TABLE FAMILY
ADD CONSTRAINT fk_ORDEN_ID
FOREIGN KEY (ORDEN_ID)
REFERENCES ORDEN(id);

ALTER TABLE GENUS
ADD FAMILY_ID INT;
ALTER TABLE GENUS
ADD CONSTRAINT fk_FAMILY_ID
FOREIGN KEY (FAMILY_ID)
REFERENCES FAMILY(id);

ALTER TABLE SPECIES
ADD GENUS_ID INT;
ALTER TABLE SPECIES
ADD CONSTRAINT fk_GENUS_ID
FOREIGN KEY (GENUS_ID)
REFERENCES GENUS(id);